---
name: typescript-language-server
description: TypeScript & JavaScript Language Server.
homepage: https://github.com/szmudo/typescript-language-server
licenses:
  - MIT
languages:
  - TypeScript
  - JavaScript
categories:
  - LSP

source:
  id: pkg:npm/typescript-language-server@szmudo/typescript-language-server
  extra_packages:
    - typescript

schemas:
  lsp: vscode:https://raw.githubusercontent.com/microsoft/vscode/main/extensions/typescript-language-features/package.json

bin:
  typescript-language-server: npm:typescript-language-server
