---
name: typescript-language-server
description: TypeScript & JavaScript Language Server.
homepage: https://github.com/szmudo/typescript-language-server
licenses:
  - MIT
languages:
  - TypeScript
  - JavaScript
categories:
  - LSP

source:
  id: pkg:github/szmudo/typescript-language-server
  build:
    staged: true
    run: |
      npm --quiet ci --no-audit --no-fund
      npm --quiet run build
      npm --quiet prune --omit=dev
      npm --quiet install --omit=dev --no-audit --no-fund typescript

schemas:
  lsp: vscode:https://raw.githubusercontent.com/microsoft/vscode/main/extensions/typescript-language-features/package.json

bin:
  typescript-language-server: node:lib/cli.mjs
